code --install-extension aaron-bond.better-comments &&
code --install-extension alefragnani.project-manager &&
code --install-extension bradlc.vscode-tailwindcss &&
code --install-extension burkeholland.simple-react-snippets &&
code --install-extension christian-kohler.npm-intellisense &&
code --install-extension christian-kohler.path-intellisense &&
code --install-extension codezombiech.gitignore &&
code --install-extension cssho.vscode-svgviewer &&
code --install-extension DavidAnson.vscode-markdownlint &&
code --install-extension dbaeumer.vscode-eslint &&
code --install-extension dracula-theme.theme-dracula &&
code --install-extension eamodio.gitlens &&
code --install-extension EditorConfig.EditorConfig &&
code --install-extension eg2.vscode-npm-script &&
code --install-extension esbenp.prettier-vscode &&
code --install-extension formulahendry.auto-rename-tag &&
code --install-extension GitHub.copilot &&
code --install-extension guilhermerodz.omni-owl &&
code --install-extension kisstkondoros.vscode-gutter-preview &&
code --install-extension miguelsolorio.fluent-icons &&
code --install-extension mikestead.dotenv &&
code --install-extension mrmlnc.vscode-scss &&
code --install-extension ms-azuretools.vscode-docker &&
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR &&
code --install-extension ms-vscode-remote.remote-wsl &&
code --install-extension ms-vsliveshare.vsliveshare &&
code --install-extension naumovs.color-highlight &&
code --install-extension oderwat.indent-rainbow &&
code --install-extension paulmolluzzo.convert-css-in-js &&
code --install-extension pflannery.vscode-versionlens &&
code --install-extension PKief.material-icon-theme &&
code --install-extension pnp.polacode &&
code --install-extension Prisma.prisma &&
code --install-extension Prisma.prisma-insider &&
code --install-extension redhat.vscode-commons &&
code --install-extension ritwickdey.LiveServer &&
code --install-extension rocketseat.theme-omni &&
code --install-extension sburg.vscode-javascript-booster &&
code --install-extension sibiraj-s.vscode-scss-formatter &&
code --install-extension steoates.autoimport &&
code --install-extension usernamehw.errorlens &&
code --install-extension VisualStudioExptTeam.vscodeintellicode &&
code --install-extension withfig.fig &&
code --install-extension yzhang.markdown-all-in-one